name: ci

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            backend/requirements.txt
            backend/requirements-dev.txt
      - name: Install deps
        run: |
          pip install -r backend/requirements.txt -r backend/requirements-dev.txt
      - name: Lint (ruff)
        run: |
          pip install ruff
          ruff check backend || true
      - name: Type check (mypy)
        run: |
          pip install mypy
          mypy --ignore-missing-imports backend || true
      - name: Tests
        run: pytest -q
      - name: Build Docker image
        run: docker build -t iso55001-backend:ci -f backend/Dockerfile .
      - name: Security scan (Trivy)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: iso55001-backend:ci
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
      - name: Ensure README updated when core changes present
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        run: |
          set -e
          BASE_SHA="${{ github.event.pull_request.base.sha }}"
          if [ -z "$BASE_SHA" ]; then BASE_SHA=$(git rev-list --max-parents=0 HEAD); fi
          CHANGED=$(git diff --name-only "$BASE_SHA"..HEAD)
          echo "$CHANGED" | sed 's/^/ - /'
          needs_docs_regex='^(backend/app/|backend/Dockerfile|backend/requirements|backend/alembic/|infrastructure/compose|infrastructure/.env|tests/|.github/workflows/)'
          if echo "$CHANGED" | grep -Eq "$needs_docs_regex"; then
            if ! echo "$CHANGED" | grep -q '^README.md$'; then
              echo "README.md not updated for core changes." >&2
              exit 1
            fi
          fi
